const fs = require('fs');
const path = require('path');
const { GoogleSpreadsheet } = require('google-spreadsheet');
const {JWT} = require('google-auth-library')

const utils = module.exports;

const outputsDir = path.join(__dirname, 'outputs');

utils.parseWAChatId = (numberString) => {
    return numberString.replace(/[^+\d]/g, '') + '@c.us';
}

//utils.parseContactNumber = (chatId) => {
  //return chatId.replace(/[^0-9]/g, '');
//}


//utils.parseContactNumber = (chatId) => {
  //  return chatId.replace(/[^+\d]/g, '');
//}
utils.parseContactNumber = (numberString) => {
    return numberString.replace(/[^+\d]/g, '') + '@c.us';
}


utils.readJSONFileSync = (filePath) => {
    const fileData = fs.readFileSync(path.join(__dirname, filePath), 'utf-8');
    return JSON.parse(fileData);
}

utils.writeJSONFileSync = (data, filename) => {
    if (!fs.existsSync(outputsDir)) {
        fs.mkdirSync(outputsDir);
    }

    data = JSON.stringify(data, null, 4);
    fs.writeFileSync(path.join(outputsDir, filename), data, 'utf-8');
}

utils.getSpreadSheetById = async (sheetId) => {
    const gsheetsAPI = require('./gsheetsapi.json');

    const {client_id, client_email, private_key} = gsheetsAPI;
    const serviceAccountAuth = new JWT({
        // env var values here are copied from service account credentials generated by google
        // see "Authentication" section in docs for more info
        email: client_email,
        key: private_key,
        clientId: client_id,
        scopes: [
          'https://www.googleapis.com/auth/spreadsheets',
        ],
      });

    const doc = new GoogleSpreadsheet(sheetId, serviceAccountAuth);

    await doc.loadInfo();

    return doc;
}
